version: '3.8'

services:
  # Nome do serviço no docker
  frontend:
    # Manda construir e ler o arquivo "Dockerfile" na mesma pasta
    build: .
    # Liga a porta 80 do Container (onde o Nginx está) para a porta 8080 do seu PC
    ports:
      - "8080:80"
    # Faz com que o contêiner sempre reinicie se seu computador desligar (automaticamente online)
    restart: unless-stopped
    # Dá um nome amistoso para ele na lista de containers do Docker Desktop
    container_name: gestao-ar-certiid-app
