server {
  # O servidor vai escutar na porta 80.
  listen 80;

  # Define a raiz onde os arquivos do site estão.
  root /usr/share/nginx/html;

  # Define o arquivo padrão a ser servido.
  index index.html;

  # Esta é a parte mais importante para SPAs (React Router).
  # Tenta encontrar o arquivo solicitado. Se não encontrar, tenta procurar
  # um diretório com o mesmo nome. Se falhar novamente, ele serve
  # o index.html. Isso passa o controle do roteamento para o React.
  location / {
    try_files $uri $uri/ /index.html;
  }
}
